### ISSUE TITLE
About experiment in article

### ISSUE THREAD

**Issue by Penation** [joeyz0z/ConZIC#11]
Hello author, I am interested in your team's work and would like to reproduce and continue the work of conzic. However, I would like to ask how conzic conducted tests on datasets such as MSCOCO. I saw that only demo code was provided on GitHub but no test code. Could you please provide more information on how the author performed dataset testing?

**Comment by joeyz0z** [comment]
You can use **run.py** to perform dataset testing by setting **--caption_img_path your_dataset_img_dir**.

**Comment by Penation** [comment]
Thank you!!!    I'll give it a try.
